name: Terraform deploy test

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

        steps:
            - uses: actions/checkout@v2            
            - uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.12.25

            - run: terraform init
            - run: terraform plan
            - run: terraform apply -auto-approve
            - run: terraform destroy -auto-approve

