name: Android build

on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest


        steps:
            - uses: actions/checkout@v2 
            - run: tree
            - name: "Build Android project"
              uses: vgaidarji/android-github-actions-build@v1.0.1
              with:
                args: "./gradlew assembleDebug"
            - run: tree              
            