name: Android build

on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js 14.x
            uses: actions/setup-node@v1
            with:
              node-version: 14.x

          - name: "Run setup"
            run: |       
              npx degit perses-org/gha .perses_gha
              cd .perses_gha/setup
              npm install
              npm start

          - run: tail -1 .perses-full.yml
              
