name: Perses Test

on:
  push:
    branches: [ master ]

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  MY_SECRET: ${{ secrets.MY_SECRET }}
  
jobs:

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        # Build
        - name: "Build Android project"
          uses: vgaidarji/android-github-actions-build@v1.0.1
          with:
            args: "./gradlew assembleDebug"
        - run: ls -l ./app/build/outputs/apk/app-debug.apk

        # Setup
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x

        - name: "Run setup"
          run: |       
            npx degit perses-org/gha .perses_gha
            cd .perses_gha/setup
            npm install
            npm start

        - run: tail -1 .perses-full.yml
        
        - run: cat .perses-credentials.yml
        
          
              
