name: Terraform deploy

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v2
            - name: Check
              run: |
                ls -l
                echo "done."


        