name: Terraform deploy

on:
  push:
    branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v2
            - name: Check
              run: |
                ls -l
                echo "done."
            - uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.12.25
                run: terraform init

        